name: Go

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2
    
    - uses: pCYSl5EDgo/cat@master
      id: get_node_version
      with:
        path: .nvmrc
        trim: true
    
    - name: Use Node.js ${{ steps.get_node_version.outputs.text }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.get_node_version.outputs.text }}
    
    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
